#!/bin/sh

uci -q batch << EOI
set network.lan.ipaddr='192.168.1.3'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.1.1'
set network.lan.broadcast='192.168.1.255'
add_list network.lan.dns='192.168.1.253'
set dhcp.lan.ignore='1'
set wireless.radio1.country='FR'
set wireless.default_radio1.ssid='OpenWrt5G'
set wireless.default_radio1.encryption='sae'
set wireless.default_radio1.key='password'
set wireless.radio1.htmode='HE160'
set wireless.radio1.channel='100'
set wireless.radio1.txpower='26'

del wireless.radio1.disabled='1'
del wireless.default_radio1.disabled='1'

set sqm.eth1.enabled='1'
set sqm.eth1.interface='lan2'
set sqm.eth1.download='200000'
set sqm.eth1.upload='20000'
set sqm.eth1.verbosity='0'

set system.cfg01e48a.zonename='Europe/Paris'
set system.cfg01e48a.timezone='CET-1CEST,M3.5.0,M10.5.0/3'
EOI

uci commit

/etc/init.d/network reload
wifi up radio1
