#!/bin/sh

secret_file=/root/secret.txt

if [ -f "$secret_file" ]; then
    password="$(cat "$secret_file")"
else
    password="password"
fi

uci -q batch << EOI
set network.lan.ipaddr='192.168.1.3'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.1.1'
set network.lan.broadcast='192.168.1.255'
add_list network.lan.dns='192.168.1.253'
set dhcp.lan.ignore='1'
set wireless.radio1.country='FR'
set wireless.default_radio1.ssid='OpenWrt5G'
set wireless.default_radio1.encryption='sae'
set wireless.default_radio1.key="$password"
set wireless.radio1.htmode='HE160'
set wireless.radio1.channel='100'
set wireless.radio1.txpower='26'

del wireless.radio1.disabled='1'
del wireless.default_radio1.disabled='1'

set sqm.eth1.enabled='1'
set sqm.eth1.interface='lan2'
set sqm.eth1.download='200000'
set sqm.eth1.upload='20000'
set sqm.eth1.verbosity='0'

set system.cfg01e48a.zonename='Europe/Paris'
set system.cfg01e48a.timezone='CET-1CEST,M3.5.0,M10.5.0/3'
EOI

uci commit

/etc/init.d/network reload
wifi up radio1

service cake-autorate enable
service cake-autorate start

# Configure profile
mkdir -p /etc/profile.d
cat << "EOF" > /etc/profile.d/uci.sh
uci() {
local UCI_CMD="${1}"
case "${UCI_CMD}" in
(validate|diff) uci_"${@}" ;;
(*) command uci "${@}" ;;
esac
}
 
uci_validate() {
local UCI_CONF="${@:-/etc/config/*}"
for UCI_CONF in ${UCI_CONF}
do if ! uci show "${UCI_CONF}" > /dev/null
then echo "${UCI_CONF}"
fi
done
}
 
uci_diff() {
local UCI_OCONF="${1:?}"
local UCI_NCONF="${2:-${1}-opkg}"
local UCI_OTEMP="$(mktemp -t uci.XXXXXX)"
local UCI_NTEMP="$(mktemp -t uci.XXXXXX)"
uci export "${UCI_OCONF}" > "${UCI_OTEMP}"
uci export "${UCI_NCONF}" > "${UCI_NTEMP}"
diff -a -b -d -y "${UCI_OTEMP}" "${UCI_NTEMP}"
rm -f "${UCI_OTEMP}" "${UCI_NTEMP}"
}
EOF
